### PR TITLE
Use Graalvm 20.1.0 in CI

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: ruromero <rromerom@redhat.com>

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
Thanks for the fix!

**Comment by matejvasek** [comment]
@ruromero was that a bug in GraalVM?

**Comment by slinkydeveloper** [comment]
This still didn't solved the issue https://travis-ci.org/github/cloudevents/sdk-java/jobs/726266414

**Comment by matejvasek** [comment]
@ruromero If you wish to debug this. You can invoke GraalVM tests event in PR: https://github.com/cloudevents/sdk-java/pull/231/commits/2b87cc7185ee57d918785d89c6541a1f7fd5cc11

**Pull request merged**
