### PR TITLE
Set correct url to naming conventions.

### PR DESCRIPTION
**Pull request by gklijs**
I noticed the url in the Java doc was not correct. As it turns out using a regex is about ten times slower for this case, so I removed that part of the commit.

### CODE REVIEW

**Comment by pierDipi** [comment]
>  also think it would be preferable to use a regex for validating the extension name.

Would you mind expanding on the why?

**Comment by gklijs** [comment]
It might be faster, although, with the expected small size of an extension name, that might not be the case. It does limit the lines of code, but the complexity of a regex might outweigh that.

**Comment by pierDipi** [comment]
> It might be faster, although, with the expected small size of an extension name, that might not be the case. It does limit the lines of code, but the complexity of a regex might outweigh that.

Exactly, a proper benchmark should be added to validate the change isn't a perf regression for various cases.

**Comment by pierDipi** [comment]
Hi @gklijs, thanks for the fix and the quick update, can you please fix the DCO check as explained here: https://github.com/cloudevents/sdk-java/pull/477/checks?check_run_id=8348631721?

**Comment by gklijs** [comment]
Should be good now.

**Pull request merged**
