### PR TITLE
Fix content-length

### LINKED ISSUE #103: incorrect content-length in http-vertx
The http-vertx determines content-length by String.length() which returns count of characters byte size.

### PR DESCRIPTION
**Pull request by matejvasek**
Fixes #103

### CODE REVIEW

**Comment by fabiojose** [comment]
@matejvasek please change this PR to fix just issue #103. And open another one to discuss the #102.

**Comment by matejvasek** [comment]
@fabiojose done

**Comment by fabiojose** [comment]
LGTM

**Comment by matejvasek** [comment]
@fabiojose since you LGTM, are you going to merge this?

**Pull request closed without merging**
