### PR TITLE
Proposal for reworking the unstructured read/write of events

### PR DESCRIPTION
**Pull request by slinkydeveloper**
This proposal comes from discussions in #143 and https://docs.google.com/document/d/1VY85Afhb-oj7m9Sm84U_f8kJp6boBS8nnuTMc9tkgO8/edit?usp=sharing

The goal of these changes is to provide an unstructured view of the event and an unstructured manner to write the event, without giving additional burden to the `CloudEvent` implementer (like `asStructuredMessage()` and `asBinaryMessage()` does). It's not a goal of this PR to address the other concerns of #143.

## `CloudEventVisitable`

`CloudEvent` implements `CloudEventVisitable`, which is an interface that defines how an unstructured visit of the message happens. `CloudEvent` provides a default implementation for it, avoiding to put this burden to the `CloudEvent` implementer.

`CloudEventVisitable` is used by `EventFormat` implementations and protocol binding implementations, keeping low the allocation cost for encoding/decoding an event.

Now users can write binary messages using:

```
event
  .visit(VertxHttpServerResponseMessageVisitor.create(req.response()));
```

While they can write structured message using:

```
GenericStructuredMessage.fromEvent(event)
  .visit(VertxHttpServerResponseMessageVisitor.create(req.response()));
```

Two helper methods are also provided for that.

## `CloudEventBuilder` and `CloudEventVisitor`/`CloudEventVisitorFactory`

`CloudEventBuilder` is the "write side" of `CloudEvent`. Concrete implementations provides "structured write" methods to write the `CloudEvent` (`withId`, `withSource`, etc) and implements the `CloudEventVisitor<CloudEvent>` interface, which provides "unstructured write" methods to create an event starting from a binary message.

## Event conversion

In a follow up pr, the visitAttributes will be used as basis to reimplement specversion conversion, in order to remove the methods on the CloudEvent interface

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
This PR has been here for more than 10 days w/o concerns. If there are no concerns raised in the next days I'm going to merge it

**Comment by olegz** [comment]
I am formally registering my objection to this merge as it was not debated for reasons that it was contingent upon the resolution or the preceding PR  - https://github.com/cloudevents/sdk-java/pull/143
Also, this merge is in clear violation of  the issue resolution process that was outlined and agreed upon by everyone on the SDK call of March 14, 2020
@duglin

**Comment by slinkydeveloper** [comment]
This PR is not blocking #143, feel free to rebase it.

**Comment by olegz** [comment]
Yes it is blocking by virtue of a community member seeking resolution for #143  - https://github.com/cloudevents/sdk-java/pull/143#issuecomment-623926276

**Comment by olegz** [comment]
Further more you can clearly see that your merge has created a merge conflict https://github.com/cloudevents/sdk-java/pull/143 essentially leaving no room for clean rebase

**Comment by duglin** [comment]
Copying from slack:
ok, so first... I apologize.  @Francesco Guardiani pinged me yesterday about this PR and his concern about it not being reviewed for 10 days - and I'm not keeping up with the SDK work that closely so it seemed like one of those cases (that we seem to get often) where someone is blocked due to other potential reviewers being busy on other stuff. Not knowing any of the history it seemed reasonable to me to have him post a msg in there with a warning that it'll be merge if no one speaks up. So, sorry about that. And I doubt @Francesco Guardiani meant to by-pass any on-going discussion or process, I'm guessing (based on my quick reading of the comments) he thought this might be a way to make incremental progress w/o necessarily waiting for all of 143 to be agreed to.

But, let's move forward... while there might be a code conflict, I think the more important question is whether there is a design conflict - and it seems like there might be.  @Francesco Guardiani and I chatted and he'll revert the PR. However, it seems like there should be some kind of deadline w.r.t. resolving 143 and 146. I'd like to suggest that we have the discussions go on for about another week and then if no resolution can be found I think it would be up to the SDK maintainers (who I think are now @fabiojose and @Francesco Guardiani) to decide/vote. In the end a decision needs to be made and I think the maintainers would be the ones to ultimately be the ones on the hook to decide.  Personally, I think a voice chat would be faster, but if you folks want to continue in the issues/PRs that's up to you - but a deadline to act as a forcing function on the talks (I hope) will help.

**Comment by olegz** [comment]
Thank you @duglin 

I 100% agree about the deadline for resolving #143 and we hope that next Thursday is going to be that day. As I outlined in the SDK meeting document we've already accepted PR suggestions for #143 from both community as well as the senior members of CNCF and will work on them before the PR is merged. 
The #143 also has a +1 vote to be merged from @fabiojose 

So, that should clear both the scope and the state we're in with regard to #143.

**Comment by slinkydeveloper** [comment]
New PR: https://github.com/cloudevents/sdk-java/pull/150

**Comment by duglin** [comment]
Is there any chance of some discussions happening before the call? I know github comments isn't ideal, but the WG's zoom channel is always available for voice chats. I'm just worried about running out of time on tomorrow's call.

**Comment by olegz** [comment]
@duglin It is going to be nearly impossible since if PR #143 is merged it would effectively invalidate most of the assumptions of this PR. That is why we were concerned about this one being merged  without any resolution on #143.  
NOTE: @fabiojose already approved #143 and all who participated in the discussion during the original call about #143 several weeks ago, with the exception @slinkydeveloper, agreed with the proposed approach as well. So I think in all fairness we need to understand the technical merits of the only objection to #143 that we have.

**Pull request merged**
