### PR TITLE
fix javadoc

### PR DESCRIPTION
**Pull request by matejvasek**

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
Did you tried to run the maven javadoc plugin locally? since you're here, can you enable it for the whole build so we make sure we catch those issues next time before merging?

**Comment by matejvasek** [comment]
I did run javadoc build.

**Comment by matejvasek** [comment]
@slinkydeveloper we could move javadoc plugin up
```diff
diff --git a/pom.xml b/pom.xml
index 1185628..30b7d4b 100644
--- a/pom.xml
+++ b/pom.xml
@@ -142,6 +142,22 @@
                 </plugin>
             </plugins>
         </pluginManagement>
+        <plugins>
+            <!-- Javadoc jar -->
+            <plugin>
+                <groupId>org.apache.maven.plugins</groupId>
+                <artifactId>maven-javadoc-plugin</artifactId>
+                <version>2.10.4</version>
+                <executions>
+                    <execution>
+                        <id>attach-javadocs</id>
+                        <goals>
+                            <goal>jar</goal>
+                        </goals>
+                    </execution>
+                </executions>
+            </plugin>
+        </plugins>
     </build>
 
     <profiles>
@@ -198,22 +214,6 @@
                             </execution>
                         </executions>
                     </plugin>
-
-                    <!-- Javadoc jar -->
-                    <plugin>
-                        <groupId>org.apache.maven.plugins</groupId>
-                        <artifactId>maven-javadoc-plugin</artifactId>
-                        <version>2.10.4</version>
-                        <executions>
-                            <execution>
-                                <id>attach-javadocs</id>
-                                <goals>
-                                    <goal>jar</goal>
-                                </goals>
-                            </execution>
-                        </executions>
-                    </plugin>
-
                     <plugin>
                         <groupId>org.apache.maven.plugins</groupId>
                         <artifactId>maven-gpg-plugin</artifactId>
```

**Comment by slinkydeveloper** [comment]
What do you mean? Can you commit this change?

**Comment by matejvasek** [comment]
https://github.com/cloudevents/sdk-java/pull/275

**Comment by slinkydeveloper** [comment]
Cool, I'm gonna merge this one meanwhile

**Pull request merged**
